### ISSUE TITLE
Risco de vazamento de credenciais

### ISSUE THREAD

**Issue by luciano-freitas** [flaviosantospqri/location-service#1]
@flaviosantospqri Boa noite meu querido, tudo bem?

Primeiramente parabéns pelo projeto viu, então estive olhando alguns pontos aqui e identifiquei essa parte como melhoria para segurança da aplicação e de suas credenciais.

Por questões de segurança te indicaria colocar essas credências em um arquivo `.env` e não fazer um commit para que não fossem enviados para o repositório, talvez poderia criar um arquivo de `.env.example` para exibir os nomes das váriaveis de ambiente e facilitar a implementação

## Como não enviar um arquivo para o commit?
Crie um arquivo chamado `.gitignore`
```
.env
```

## como utilizar a env no projeto
```.js
 const firebaseConfig = { 
   apiKey: process.env.API_KEY, 
   authDomain: process.env.AUTH_DOMAIN, 
   ...
 }; 
```

## Local no projeto 
https://github.com/flaviosantospqri/location-service/blob/9893663a0bfba0d3cf568a52c876332aaf6b310d/src/services/firebase/index.js#L8-L15

**Comment by flaviosantospqri** [comment]
Muito obrigado por sua observação @luciano-freitas, com certeza é algo que vou revisar. O projeto está ainda no início, mesmo assim já era para eu ter o criado com o git ignore configurado. Novamente, muito obrigado. Logo subo com as correções de segurança necesárias.
